# Generated by Django 4.2.28 on 2026-04-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'Complete'), (3, 'Upcoming'), (2, 'Pending'), (0, 'Cancelled')], default=2)),
            ],
        ),
    ]
