# Generated by Django 4.2.28 on 2026-08-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_service_price_service_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cancellation_policy',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
