# Generated by Django 4.2.28 on 2026-04-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_experience', models.IntegerField(default=0)),
                ('credentials', models.TextField(blank=True, default='')),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
