# Generated by Django 6.0 on 2025-12-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountantprofile",
            name="years_experience",
            field=models.IntegerField(default=0),
        ),
    ]
