# Generated by Django 6.0 on 2025-12-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountants", "0002_alter_accountantprofile_years_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountantprofile",
            name="complete",
            field=models.BooleanField(default=False),
        ),
    ]
