# Generated by Django 4.2.28 on 2026-07-18 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accountants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountantprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountantprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
