# Generated by Django 6.0 on 2025-12-31 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountants", "0003_accountantprofile_complete"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accountantprofile",
            old_name="complete",
            new_name="profile_complete",
        ),
        migrations.AlterField(
            model_name="accountantprofile",
            name="bio",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="accountantprofile",
            name="credentials",
            field=models.CharField(blank=True, default=""),
        ),
    ]
