# Generated by Django 6.0 on 2026-01-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accountants",
            "0004_rename_complete_accountantprofile_profile_complete_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountantprofile",
            name="credentials",
            field=models.TextField(blank=True, default=""),
        ),
    ]
