# Generated by Django 4.2.28 on 2026-08-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountants', '0004_accountantprofile_firm_name_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountantprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='accountantprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='accountantprofile',
            name='service_scope',
            field=models.CharField(choices=[('local', 'Local / in-person'), ('remote', 'Remote'), ('nationwide', 'Nationwide')], default='local', max_length=20),
        ),
    ]
