# Generated by Django 4.2.28 on 2026-09-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountants', '0005_map_discovery_coords_service_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountantprofile',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
    ]
