# Generated by Django 4.2.28 on 2026-09-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountants', '0007_backfill_publication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountantprofile',
            name='headline',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='accountantprofile',
            name='industries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='accountantprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='accountantprofile',
            name='license_information',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='accountantprofile',
            name='offers_in_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountantprofile',
            name='offers_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountantprofile',
            name='website',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
