# Generated by Django 4.2.28 on 2026-09-10 02:08

import accountants.profile_photo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountants', '0009_backfill_availability_from_service_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountantprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to=accountants.profile_photo.accountant_profile_photo_upload_to),
        ),
    ]
