# Generated by Django 6.0 on 2026-01-19 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_remove_conversation_recipient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="inquiry",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation",
                to="chats.inquiry",
            ),
        ),
    ]
