# Generated by Django 6.0 on 2026-02-08 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_alter_conversation_inquiry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inquiry",
            name="accountant",
        ),
        migrations.RemoveField(
            model_name="inquiry",
            name="client",
        ),
        migrations.RemoveField(
            model_name="inquiry",
            name="service",
        ),
    ]
