# Generated by Django 4.2.28 on 2026-07-19 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0006_alter_inquiry_status'),
        ('chats', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='inquiries.inquiry'),
        ),
    ]
