# Generated by Django 6.0 on 2026-02-08 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0004_remove_inquiry_accountant_remove_inquiry_client_and_more"),
        ("inquiries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="inquiry",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation",
                to="inquiries.inquiry",
            ),
        ),
        migrations.DeleteModel(
            name="Inquiry",
        ),
    ]
