# Generated by Django 4.2.28 on 2026-04-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inquiry',
            constraint=models.UniqueConstraint(fields=('client', 'service'), name='unique_client_service_inquiry'),
        ),
    ]
