# Generated by Django 4.2.28 on 2026-07-19 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
        ('inquiries', '0004_conversationreadstate'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inquiry',
            name='unique_client_service_inquiry',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='services.service'),
        ),
        migrations.AddConstraint(
            model_name='inquiry',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open'), ('service__isnull', False)), fields=('client', 'accountant', 'service'), name='unique_open_inquiry_with_service'),
        ),
        migrations.AddConstraint(
            model_name='inquiry',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open'), ('service__isnull', True)), fields=('client', 'accountant'), name='unique_open_general_inquiry'),
        ),
    ]
