# Generated by Django 6.0 on 2025-12-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField()),
                ("password", models.CharField()),
                ("user_id", models.IntegerField()),
                ("is_accountant", models.BooleanField(default=False)),
            ],
        ),
    ]
